#!/usr/bin/env bash
#
# diffdir - A script to compare files in two directories
#
# GitHub: https://github.com/doppelar0n/diffdir
# License: MIT
#

# Ensure exactly two arguments (source and destination directory paths) are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <source_directory> <destination_directory>"
    exit 1
fi

# Assign the arguments to meaningful variable names
SOURCE_DIR=$1
DESTINATION_DIR=$2

# Check if the source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo "Error: Source Directory $SOURCE_DIR does not exist."
    exit 1
fi

# Check if the destination directory exists
if [ ! -d "$DESTINATION_DIR" ]; then
    echo "Error: Destination Directory $DESTINATION_DIR does not exist."
    exit 1
fi

EXIT_CODE=0

FIND_TYPE="fd"
FIND_CONDITION=""

for type in $(echo $FIND_TYPE | fold -w1); do
    case "$type" in
        f) FIND_CONDITION="$FIND_CONDITION -type f -o" ;;
        d) FIND_CONDITION="$FIND_CONDITION -type d -o" ;;
        l) FIND_CONDITION="$FIND_CONDITION -type l -o" ;;
        c) FIND_CONDITION="$FIND_CONDITION -type c -o" ;;
        b) FIND_CONDITION="$FIND_CONDITION -type b -o" ;;
        p) FIND_CONDITION="$FIND_CONDITION -type p -o" ;;
        s) FIND_CONDITION="$FIND_CONDITION -type s -o" ;;
        *) echo "Unknown find -type: $type"; exit 1 ;;
    esac
done

FIND_CONDITION=${FIND_CONDITION::-3}

# Check if listings from both directories are identical
if diff <(find "$SOURCE_DIR" \( $FIND_CONDITION \)|sed "s|$SOURCE_DIR||") <(find "$DESTINATION_DIR" \( $FIND_CONDITION \)|sed "s|$DESTINATION_DIR||") > /dev/null; then
    :
else
    echo "Differences between the $SOURCE_DIR and $DESTINATION_DIR found."
    diff <(find "$SOURCE_DIR" \( $FIND_CONDITION \)|sed "s|$SOURCE_DIR||") <(find "$DESTINATION_DIR" \( $FIND_CONDITION \)|sed "s|$DESTINATION_DIR||")
    EXIT_CODE=1
fi

while read -r FILE_IN_SOURCE_DIR; do
    FILE_IN_DESTINATION_DIR="${FILE_IN_SOURCE_DIR/$SOURCE_DIR/$DESTINATION_DIR}"

    # Check if the corresponding file exists in the destination directory
    if [ -f "$FILE_IN_DESTINATION_DIR" ]; then
        if diff "$FILE_IN_SOURCE_DIR" "$FILE_IN_DESTINATION_DIR" > /dev/null; then
            :
	    else
            echo "File $FILE_IN_SOURCE_DIR and $FILE_IN_DESTINATION_DIR are different"
            EXIT_CODE=1
        fi
    else
        echo "File $FILE_IN_DESTINATION_DIR does not exist in directory $DESTINATION_DIR."
        EXIT_CODE=1
    fi
done < <(find "$SOURCE_DIR" -type f)

exit $EXIT_CODE
