name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Bats
        run: sudo apt-get install bats

      - name: Run tests
        run: ./test/bats/bin/bats test/test_diffdir.bats
